# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13


jobs:
  docker:
      # specify the version you desire here
      - image: circleci/node:10.15.3
  
  - checkout

  working_directory: ~/repo

  - restore_cache:
      keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

  - run: yarn install

  - save_cache:
      paths:
        - node_modules
      key: v1-dependencies-{{ checksum "package.json" }}
  test:

    steps:
      - run: yarn test

  build:
      - run: yarn build

  deploy:
     - run:
          name: "Install missing library on awscli"
          command: sudo apt-get install -y libpython-dev 
      - aws-cli/install

      - aws-cli/configure

      # deploy
      - run:
          name: "Deploy"
          command: aws s3 sync build s3://spork-circleci-test/spork --delete
